[package]
authors = ["David O'Connor <the_alchemist@fastmail.com>"]
name = "dronecan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fdcan = "0.1.2"
# todo: Hardcoded for Can type.
cortex_m = "^0.7.7"
stm32-hal2 = { path = "../../stm32-hal", feature = "g431" }

# To parse enums from their integer repr
num_enum = { version = "^0.6.0", default_features = false }

nb = "^1.1.0"  # For use with Fdcan lib's infallible type.

[features]
g4 = ["fdcan/fdcan_g0_g4_l5",  "stm32-hal2/g431", "stm32-hal2/can_fd_g"]
h7 = ["fdcan/fdcan_h7", "stm32-hal2/h743v", "stm32-hal2/can_fd_h"]

